---
- hosts: all
  tasks:
    - name: Setup soft {{ item }}
      package:
        state: present
        name: {{ item }}
      loop:
        - vim
        - sddm 
        - sddm-kcm
        - xorg 
        - xorg-xinit 
        - mesa
        - gnome 
        - gnome-extra
        - code
        - dhcpcd
        - git
        - telegram-desktop
        - xterm
        - zsh
        - wget 
        - curl
        - npm
        - tilix
        - ncdu
        - slack-desktop
        - bat
        - exa
        - ripgrip
        - oh-my-zsh-git
    - name: Start and Enable sddm
      systemd:
        name: sddm
        state: started
        enabled: yes
    - name: git clone smartgit
        git:
          repo: https://aur.archlinux.org/smartgit.git
          dest: {{ lookup('env', 'HOME') }}/.build/smartgit
    - name: Install smartgit
        command:
          chdir: {{ lookup('env', 'HOME') }}/.build/smartgit
          cmd: makepkg -is 
