---
- hosts: all
  vars:
    repo_list: "{{ lookup('file', '/home/ivan/aaa/git_soft.txt').split()  }}"
    soft_list: "{{ lookup('file', '/home/ivan/aaa/soft.list.txt').split() }}"
    backup_dconf_file: "/home/ivan/gnome.backup.dconf"
  tasks:
    # - name: Setup softs list
    #   package:
    #     state: present
    #     name: "{{ item }}"
    #   loop: "{{ soft_list }}"
    # - name: Start and Enable sddm  
    #   systemd:
    #     name: sddm
    #     state: started
    #     enabled: yes
    # - name: Install soft from arch linux git repo
    #   become: yes
    #   become_user: "{{ user_name }}"
    #   block:
    #     - name: Create mountpoint for boot volume
    #       file:
    #         path: "{{ lookup('env', 'HOME') }}/.build"
    #         state: directory
    #     - name: git clone aur soft
    #       git:
    #         repo: "{{ item }}" 
    #         dest: "{{ lookup('env', 'HOME') }}/.build/{{ folder_name | trim  }}"
    #         force: yes
    #       vars:
    #         folder_name: "{{ item | urlsplit('path') | basename | regex_replace('(.*)\\.git$', '\\1') }} "
    #       loop: "{{ repo_list }}"
    #     - name: Install smartgit
    #       command:
    #         chdir: "{{ lookup('env', 'HOME') }}/.build/{{ folder_name | trim }}"
    #         cmd: makepkg --install --noconfirm --force --clean --syncdeps
    #       vars:
    #         folder_name: "{{ item | urlsplit('path') | basename | regex_replace('(.*)\\.git$', '\\1') }} "
    #       loop: "{{ repo_list }}"
    - name: Copy gnome.backup.dconf
      copy:
        src: "gnome.backup.dconf"
        dest: "{{ backup_dconf_file }}"

    - name: Restory dconf backup
      shell: "dconf load -f / < {{ backup_dconf_file }}"